# Generated by Django 2.2.2 on 2019-07-05 09:15

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import transactional_email.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(auto_now_add=True)),
                ('from_email', models.EmailField(max_length=254)),
                ('to_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=128)),
                ('body', models.TextField(max_length=1024)),
                ('ok', models.BooleanField(default=True)),
                ('service', models.CharField(blank=True, help_text='Which services was used to send this e-mail. Eg: sendgrid, mailgun, etc', max_length=20, null=True)),
                ('message_id', models.CharField(blank=True, help_text='Optional message ID assigned by the service.', max_length=255, null=True)),
            ],
            options={
                'ordering': ['-when'],
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='transactional_email/', help_text='Example: "transactional_email/welcome.html"', max_length=255, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='MailConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of this mail configuration. Eg: admin.notification', max_length=255, unique=True)),
                ('description', models.CharField(blank=True, help_text='More verbose description about the Transactional E-mail', max_length=255, null=True)),
                ('subject', models.CharField(help_text='Subject of the e-mail', max_length=255)),
                ('from_email', models.CharField(help_text='From e-mail. Example: Jeffrey Lebowski <jeffrey@dudeism.com>', max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transactional_email.Template')),
            ],
            options={
                'ordering': ('-name', '-updated'),
            },
        ),
        migrations.CreateModel(
            name='TemplateVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=transactional_email.models._default_name, help_text='Unique name for this template version', max_length=255, verbose_name='Version Name')),
                ('active', models.BooleanField(default=False, help_text='Active version')),
                ('content', models.TextField(blank=True, help_text='Content of the e-mail template')),
                ('test_data', django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='JSON structure with test data view and send test e-mails')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transactional_email.Template')),
            ],
            options={
                'ordering': ('-active', '-updated'),
                'unique_together': {('template', 'name')},
            },
        ),
    ]
