# Generated by Django 2.2.2 on 2019-07-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactional_email', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='service',
            field=models.CharField(blank=True, help_text='Which services was used to send this e-mail. Eg: sendgrid, mailgun, etc', max_length=100, null=True),
        ),
    ]
